clusters=primary,secondary

primary.bootstrap.servers=primary-kafka-1:9092,primary-kafka-2:9092,primary-kafka-3:9092
secondary.bootstrap.servers=secondary-kafka-1:9092,secondary-kafka-2:9092,secondary-kafka-3:9092

primary.security.protocol=SASL_SSL
primary.sasl.mechanism=PLAIN
primary.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="mirror" password="mirror-secret";
primary.ssl.truststore.location=/etc/kafka/client/kafka.truststore.jks
primary.ssl.truststore.password=changeit
primary.ssl.endpoint.identification.algorithm=https

secondary.security.protocol=SASL_SSL
secondary.sasl.mechanism=PLAIN
secondary.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="mirror" password="mirror-secret";
secondary.ssl.truststore.location=/etc/kafka/client/kafka.truststore.jks
secondary.ssl.truststore.password=changeit
secondary.ssl.endpoint.identification.algorithm=https

primary->secondary.enabled=true
secondary->primary.enabled=false
primary->secondary.topics=products.filtered,client.events
primary->secondary.groups=.*

replication.factor=3
offset-syncs.topic.replication.factor=3
heartbeats.topic.replication.factor=3
checkpoints.topic.replication.factor=3

emit.heartbeats.enabled=true
emit.checkpoints.enabled=true
sync.group.offsets.enabled=true
sync.topic.configs.enabled=true
refresh.topics.enabled=true
refresh.topics.interval.seconds=10
refresh.groups.enabled=true
refresh.groups.interval.seconds=10
