KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_shop="shop-secret"
  user_client="client-secret"
  user_processor="processor-secret"
  user_mirror="mirror-secret"
  user_connect="connect-secret"
  user_storage="storage-secret"
  user_analytics="analytics-secret";
};

Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="kafka-zookeeper-secret";
};
